#!/usr/bin/env python3

import cv2 as cv
import numpy as np
import sys

opcion = input("1. Segmentar foto\n2.Segmentar desde la webcam\n:")
color_rgb = np.uint8([[[170,213,12]]])

color_hsv = cv.cvtColor(color_rgb,cv.COLOR_BGR2HSV)
print(color_hsv)
upperColor = color_hsv[0][0][0] + 10, 255, 255

lowerColor = color_hsv[0][0][0] - 10, 10, 10
lowerColor = np.array([lowerColor[0], lowerColor[1], lowerColor[2]])
upperColor= np.array([upperColor[0], upperColor[1], upperColor[2]])
upperColor = np.uint8([[upperColor]])
print(upperColor)
color_rgb2 = cv.cvtColor(upperColor, cv.COLOR_HSV2BGR)
print(color_rgb2)
print(lowerColor)
print(upperColor)
# Segmentar una imagen predeterminada
if opcion == "1":
    img = cv.imread(cv.samples.findFile("verde.jpeg"))
    img = cv.resize(img, (1080, 920))
    colorDetected = cv.inRange(img, lowerColor,upperColor)
    cv.imshow("Display window", img)
    cv.imshow("COLOR", colorDetected)
    k = cv.waitKey(0)
else:
    # Segmentar de la webcam
    img = cv.VideoCapture(0)
    while (img.isOpened()):
        ret, frame = img.read()
        cv.imshow('webCam', frame)
        colorDetected = cv.inRange(img, lowerColor,upperColor )
        cv.imshow("COLOR", colorDetected)
        if (cv.waitKey(1) == ord('e')):
            break
    img.release()
    cv.destroyAllWindows()

